<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <Il2CppInteropVersion>1.5.1</Il2CppInteropVersion>
    <UnityProxyDir Condition="'$(UnityProxyDir)'==''"
      >$(MSBuildThisFileDirectory)Utility\lib\Proxies</UnityProxyDir>
  </PropertyGroup>
</Project>
