<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Utility.Notifications.Ugui</AssemblyName>
    <RootNamespace>Utility.Notifications.Ugui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Utility\Utility.csproj" Private="false" />
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(UnityProxyDir)\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityProxyDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(UnityProxyDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(UnityProxyDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(UnityProxyDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Il2CppInterop.Runtime" Version="$(Il2CppInteropVersion)">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="CopyOptionalRendererNextToUtility" AfterTargets="Build">
    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFiles="$(MSBuildProjectDirectory)\..\Utility\bin\$(Configuration)\$(TargetFramework)\$(TargetFileName)"
      SkipUnchangedFiles="true"
    />
  </Target>
</Project>
